/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.tads.pi.VIEW;

import br.senac.tads.pi.CONTROLLER.ProdutoController;
import br.senac.tads.pi.MODEL.ProdutoModel;
import br.senac.tads.pi.DAO.ProdutoDAO;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria.imbeserra
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form Gerenciamento_Produtos_View
     */
    private final ProdutoDAO produtoDao = new ProdutoDAO();

    public MainView() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        setTitle("Gerenciador de Produtos");
        limpaCampos();
        carregarTabela();
    }

    //Limpar campos
    public void limpaCampos() {
        this.txtNome.setText("");
        this.txtDesc.setText("");
        this.txtPrecoCompra.setText("");
        this.txtPrecoVenda.setText("");
        this.txtQtde.setText("");
        this.btnGroupDisponibilidade.clearSelection();
    }

    //Carregar tabela de produtos automaticamente ao abrir software
    public void carregarTabela() {

        ArrayList<String[]> linhasRegistro = ProdutoController.consultar();

        DefaultTableModel tmProdutos = new DefaultTableModel();
        tmProdutos.addColumn("Código");
        tmProdutos.addColumn("Nome");
        tmProdutos.addColumn("Descrição");
        tmProdutos.addColumn("Preço de Compra");
        tmProdutos.addColumn("Preço de Venda");
        tmProdutos.addColumn("Quantidade");
        tmProdutos.addColumn("Disponibilidade");
        tmProdutos.addColumn("Data");

        tblDados.setModel(tmProdutos);

        for (String[] c : linhasRegistro) {
            tmProdutos.addRow(c);
        }

    }

    public boolean validarFormulario() {
        if (txtNome.getText().isEmpty()
                && txtDesc.getText().isEmpty()
                && txtPrecoCompra.getText().isEmpty()
                && txtPrecoVenda.getText().isEmpty()
                && txtQtde.getText().isEmpty()) {
            return false;

        } else {
            return true;
        }

    }

    private ProdutoModel inserirDados(ProdutoModel produto) {

        if (validarFormulario()) {
            produto.setNome(txtNome.getText());
            produto.setDesc(txtDesc.getText());
            produto.setPrecoCompra(Double.parseDouble(txtPrecoVenda.getText()));
            produto.setPrecoVenda(Double.parseDouble(txtPrecoCompra.getText()));
            produto.setQtde(Integer.parseInt(txtQtde.getText()));
            boolean botao = true;
            if (rbdSIm.isSelected()) {
                botao = true;
            }
            if (rbdNao.isSelected()) {
                botao = false;
            }
            produto.setDisponibilidade(botao);
            Timestamp data = new Timestamp(System.currentTimeMillis());
            produto.setDataCadastro(data);

            return produto;
        } else {
            JOptionPane.showMessageDialog(null, "Campos Obrigatorios não preenchidos");
            return null;
        }
    }

    private ProdutoModel alterarDados(ProdutoModel produto) {

        if (validarFormulario()) {
            produto.setNome(txtNome.getText());
            produto.setDesc(txtDesc.getText());
            produto.setPrecoCompra(Double.parseDouble(txtPrecoVenda.getText()));
            produto.setPrecoVenda(Double.parseDouble(txtPrecoCompra.getText()));
            produto.setQtde(Integer.parseInt(txtQtde.getText()));
            boolean botao = true;
            if (rbdSIm.isSelected()) {
                botao = true;
            }
            if (rbdNao.isSelected()) {
                botao = false;
            }
            produto.setDisponibilidade(botao);
            produto.setId(Integer.parseInt(lblID.getText()));

            return produto;
        } else {
            JOptionPane.showMessageDialog(null, "Campos Obrigatorios não preenchidos");
            return null;
        }
    }

    private ProdutoModel excluirDados(ProdutoModel produto) {

        produto.setId(Integer.parseInt(lblID.getText()));
        return produto;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDisponibilidade = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        pnlDados = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblPrecoCompra = new javax.swing.JLabel();
        lblQtde = new javax.swing.JLabel();
        lblPrecoVenda = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        lblDesc = new javax.swing.JLabel();
        lblDisponibilidade = new javax.swing.JLabel();
        rbdSIm = new javax.swing.JRadioButton();
        rbdNao = new javax.swing.JRadioButton();
        ckbCategoria1 = new javax.swing.JCheckBox();
        ckbCategoria2 = new javax.swing.JCheckBox();
        ckbCategoria3 = new javax.swing.JCheckBox();
        ckbCategoria4 = new javax.swing.JCheckBox();
        ckbCategoria5 = new javax.swing.JCheckBox();
        lblCategoria = new javax.swing.JLabel();
        txtPrecoCompra = new javax.swing.JTextField();
        txtPrecoVenda = new javax.swing.JTextField();
        txtQtde = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnPesquisaID = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Produtos");

        pnlBackground.setBackground(new java.awt.Color(50, 39, 58));

        pnlDados.setBackground(new java.awt.Color(50, 39, 58));
        pnlDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblNome.setFont(new java.awt.Font("Kalinga", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(240, 240, 240));
        lblNome.setText("Nome do produto:");
        lblNome.setAlignmentX(0.5F);

        lblPrecoCompra.setFont(new java.awt.Font("Kalinga", 1, 12)); // NOI18N
        lblPrecoCompra.setForeground(new java.awt.Color(240, 240, 240));
        lblPrecoCompra.setText("Preço de Compra:");
        lblPrecoCompra.setAlignmentX(0.5F);

        lblQtde.setFont(new java.awt.Font("Kalinga", 1, 12)); // NOI18N
        lblQtde.setForeground(new java.awt.Color(240, 240, 240));
        lblQtde.setText("Quantidade:");
        lblQtde.setAlignmentX(0.5F);

        lblPrecoVenda.setFont(new java.awt.Font("Kalinga", 1, 12)); // NOI18N
        lblPrecoVenda.setForeground(new java.awt.Color(240, 240, 240));
        lblPrecoVenda.setText("Preço de Venda:");
        lblPrecoVenda.setAlignmentX(0.5F);

        txtNome.setToolTipText("Nome do produto");

        txtDesc.setToolTipText("Descrição detalhada do produto");

        lblDesc.setFont(new java.awt.Font("Kalinga", 1, 12)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(240, 240, 240));
        lblDesc.setText("Descrição do produto:");
        lblDesc.setAlignmentX(0.5F);

        lblDisponibilidade.setFont(new java.awt.Font("Kalinga", 1, 12)); // NOI18N
        lblDisponibilidade.setForeground(new java.awt.Color(240, 240, 240));
        lblDisponibilidade.setText("Disponibilidade:");
        lblDisponibilidade.setAlignmentX(0.5F);

        btnGroupDisponibilidade.add(rbdSIm);
        rbdSIm.setForeground(new java.awt.Color(255, 255, 255));
        rbdSIm.setSelected(true);
        rbdSIm.setText("SIM");

        btnGroupDisponibilidade.add(rbdNao);
        rbdNao.setForeground(new java.awt.Color(255, 255, 255));
        rbdNao.setText("NÃO");

        ckbCategoria1.setText("1");

        ckbCategoria2.setText("2");
        ckbCategoria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbCategoria2ActionPerformed(evt);
            }
        });

        ckbCategoria3.setText("3");
        ckbCategoria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbCategoria3ActionPerformed(evt);
            }
        });

        ckbCategoria4.setText("4");

        ckbCategoria5.setText("5");

        lblCategoria.setFont(new java.awt.Font("Kalinga", 1, 12)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(240, 240, 240));
        lblCategoria.setText("Categoria:");
        lblCategoria.setAlignmentX(0.5F);

        txtPrecoCompra.setToolTipText("Descrição detalhada do produto");

        txtPrecoVenda.setToolTipText("Descrição detalhada do produto");

        txtQtde.setToolTipText("Descrição detalhada do produto");

        lblID.setFont(new java.awt.Font("Kalinga", 1, 12)); // NOI18N
        lblID.setForeground(new java.awt.Color(240, 240, 240));
        lblID.setAlignmentX(0.5F);

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblDesc)
                    .addComponent(lblPrecoCompra)
                    .addComponent(lblPrecoVenda)
                    .addComponent(lblQtde)
                    .addComponent(lblDisponibilidade))
                .addGap(20, 20, 20)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addComponent(rbdSIm)
                        .addGap(18, 18, 18)
                        .addComponent(rbdNao)
                        .addGap(46, 46, 46)
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(ckbCategoria1)
                        .addGap(18, 18, 18)
                        .addComponent(ckbCategoria2)
                        .addGap(18, 18, 18)
                        .addComponent(ckbCategoria3)
                        .addGap(18, 18, 18)
                        .addComponent(ckbCategoria4)
                        .addGap(15, 15, 15)
                        .addComponent(ckbCategoria5))
                    .addComponent(txtDesc)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(txtPrecoCompra)
                    .addComponent(txtPrecoVenda)
                    .addComponent(txtQtde))
                .addGap(20, 20, 20))
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtde, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisponibilidade, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(rbdSIm)
                    .addComponent(rbdNao)
                    .addComponent(ckbCategoria1)
                    .addComponent(ckbCategoria2)
                    .addComponent(ckbCategoria3)
                    .addComponent(ckbCategoria4)
                    .addComponent(ckbCategoria5)
                    .addComponent(lblCategoria)
                    .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        btnNovo.setBackground(new java.awt.Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Kalinga", 1, 11)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(102, 0, 102));
        btnNovo.setText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterar.setFont(new java.awt.Font("Kalinga", 1, 11)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(102, 0, 102));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Kalinga", 1, 11)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(102, 0, 102));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultar.setFont(new java.awt.Font("Kalinga", 1, 11)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(102, 0, 102));
        btnConsultar.setText("Consultar");
        btnConsultar.setAlignmentY(0.0F);

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDados);

        pnlTitle.setBackground(new java.awt.Color(102, 0, 102));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Gerenciamento de Estoque");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnPesquisaID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPesquisaID.setForeground(new java.awt.Color(255, 51, 0));
        btnPesquisaID.setText("Pesquisar por ID");
        btnPesquisaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(pnlDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPesquisaID)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar)
                        .addGap(29, 29, 29))))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnNovo)
                    .addComponent(btnPesquisaID))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
// FALTA IMPLEMENTAR COM CONTROOLER
//       // Timestamp data = new Timestamp(System.currentTimeMillis());
//        ProdutoController.getProdutoController().inserir(
//                txtNome.getText(),
//                txtDesc.getText(),
//                Double.parseDouble(txtFormCompra.getText()),
//                Double.parseDouble(txtFormVenda.getText()),
//                Integer.parseInt(txtFormQtd.getText()),
//                btnGroupDisponibilidade.getSelection().toString(),
//                data);

//IMPLEMENTANDO SEM CONTROOLER
        try {
            ProdutoModel produto = inserirDados(new ProdutoModel());
            if (produto != null) {
                produtoDao.Inserir(produto);
                carregarTabela();
                limpaCampos();
            }
        } catch (SQLException ex) {
            carregarTabela();
            limpaCampos();
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            ProdutoModel produto = alterarDados(new ProdutoModel());
            produtoDao.Alterar(produto);
            carregarTabela();
            limpaCampos();

        } catch (SQLException ex) {
            carregarTabela();
            limpaCampos();
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String str = lblID.toString();
        int ID = Integer.parseInt(str);
        try {
            ProdutoModel produto = excluirDados(new ProdutoModel());
            produtoDao.Excluir(produto);
            carregarTabela();
            limpaCampos();

        } catch (SQLException ex) {
            carregarTabela();
            limpaCampos();
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaIDActionPerformed

    private void ckbCategoria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbCategoria2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbCategoria2ActionPerformed

    private void ckbCategoria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbCategoria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbCategoria3ActionPerformed

    private void tblDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDadosMouseClicked
        // evento de clicar na linah da tabela
        // e as informações ocuparem txtForm

        int linha = tblDados.getSelectedRow();
        lblID.setText(tblDados.getValueAt(linha, 0).toString());
        txtNome.setText(tblDados.getValueAt(linha, 1).toString());
        txtDesc.setText(tblDados.getValueAt(linha, 2).toString());
        txtPrecoCompra.setText(tblDados.getValueAt(linha, 3).toString());
        txtPrecoVenda.setText(tblDados.getValueAt(linha, 4).toString());
        txtQtde.setText(tblDados.getValueAt(linha, 5).toString());
        boolean disp = Boolean.getBoolean(tblDados.getValueAt(linha, 6).toString());
        lblID.setVisible(false);
        if (disp == true) {
            rbdSIm.isSelected();
        } else {
            rbdNao.isSelected();
        }

    }//GEN-LAST:event_tblDadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup btnGroupDisponibilidade;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisaID;
    private javax.swing.JCheckBox ckbCategoria1;
    private javax.swing.JCheckBox ckbCategoria2;
    private javax.swing.JCheckBox ckbCategoria3;
    private javax.swing.JCheckBox ckbCategoria4;
    private javax.swing.JCheckBox ckbCategoria5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDisponibilidade;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPrecoCompra;
    private javax.swing.JLabel lblPrecoVenda;
    private javax.swing.JLabel lblQtde;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JRadioButton rbdNao;
    private javax.swing.JRadioButton rbdSIm;
    private javax.swing.JTable tblDados;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPrecoCompra;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtQtde;
    // End of variables declaration//GEN-END:variables
}
